<?php
namespace Tests\Integration;
use App\Models\{Invoice,Company,User};
use App\Services\Receivables\NativeCashFlowForecast;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\{Bus,DB,Mail};
use Symfony\Component\HttpKernel\Exception\HttpException;
use Tests\{MockAccountData,TestCase};
class CashFlowForecastTest extends TestCase
{
    use MockAccountData,DatabaseTransactions;
    protected function setUp(): void {parent::setUp();Bus::fake()->except([\App\Jobs\Company\CreateCompanyTaskStatuses::class]);Mail::fake();$this->makeTestData();Bus::fake();config(['ninja.cash_flow_forecast_enabled'=>true]);$s=$this->client->settings;$s->currency_id='1';$this->client->settings=$s;$this->client->saveQuietly();DB::table('invoices')->where('id',$this->invoice->id)->update(['status_id'=>Invoice::STATUS_SENT,'balance'=>'12.000000','due_date'=>'2026-10-03','is_deleted'=>false,'deleted_at'=>null]);}
    private function input(): array {return ['start_date'=>'2026-10-02','end_date'=>'2026-10-04','scenarios'=>[['version'=>'base_v1','collection_basis_points'=>5000,'delay_days'=>0,'opening_minor_by_currency'=>['USD'=>'100'],'planned_outflows'=>[['date'=>'2026-10-04','currency'=>'USD','amount_minor'=>'50']]]]];}
    private function rows(): array {$out=[];foreach(['invoices','payments','paymentables','clients','company_ledgers','activities','jobs']as$t)$out[$t]=DB::table($t)->orderBy('id')->get()->toJson();return $out;}
    public function testNativeForecastUsesExactCurrentBalancesAndHasNoEffects(): void {$rows=$this->rows();$r=(new NativeCashFlowForecast())->build(auth()->user(),$this->input());$this->assertSame('NONE',$r['write_authority']);$this->assertSame('600',$r['scenarios'][0]['totals_by_currency']['USD']['inflow_minor']);$this->assertSame('650',$r['scenarios'][0]['totals_by_currency']['USD']['closing_minor']);$this->assertSame($rows,$this->rows());Bus::assertNothingDispatched();Mail::assertNothingSent();Mail::assertNothingQueued();}
    public function testCurrentBalanceChangeChangesForecastAndProvenance(): void {$service=new NativeCashFlowForecast();$a=$service->build(auth()->user(),$this->input());DB::table('invoices')->where('id',$this->invoice->id)->update(['balance'=>'10.000000']);$b=$service->build(auth()->user(),$this->input());$this->assertNotSame($a['source_snapshot_sha256'],$b['source_snapshot_sha256']);$this->assertSame('500',$b['scenarios'][0]['totals_by_currency']['USD']['inflow_minor']);}
    public function testRevokedRoleCannotForecastAgain(): void {$m=auth()->user()->token()->cu;$m->is_admin=false;$m->is_owner=false;$m->permissions='';$m->save();$this->expectException(HttpException::class);(new NativeCashFlowForecast())->build(auth()->user(),$this->input());}
    public function testDisabledCapabilityRejects(): void {config(['ninja.cash_flow_forecast_enabled'=>false]);$this->expectException(HttpException::class);(new NativeCashFlowForecast())->build(auth()->user(),$this->input());}
    public function testProductionRejectsEvenEnabled(): void {$this->app->instance('env','production');$this->expectException(HttpException::class);(new NativeCashFlowForecast())->build(auth()->user(),$this->input());}
    public function testAuthenticatedApiRechecksDatabaseRoleAfterFirstRead(): void {$h=['X-API-TOKEN'=>$this->token,'X-Requested-With'=>'XMLHttpRequest'];$this->postJson('/api/v1/reports/cash_flow_forecast',$this->input(),$h)->assertOk();DB::table('company_user')->where('company_id',$this->company->id)->where('user_id',$this->user->id)->update(['is_admin'=>false,'is_owner'=>false,'permissions'=>'']);$this->postJson('/api/v1/reports/cash_flow_forecast',$this->input(),$h)->assertUnauthorized();}
    public function testAuthenticatedApiRejectsCallerCompanyAndDoesNotDispatch(): void {$h=['X-API-TOKEN'=>$this->token,'X-Requested-With'=>'XMLHttpRequest'];$this->postJson('/api/v1/reports/cash_flow_forecast',$this->input(),$h)->assertOk()->assertJsonPath('write_authority','NONE');$this->postJson('/api/v1/reports/cash_flow_forecast',$this->input()+['company_id'=>'999'],$h)->assertUnprocessable();Bus::assertNothingDispatched();Mail::assertNothingSent();}
    public function testOtherOwnersAndTenantsDoNotEnterForecast(): void {$m=auth()->user()->token()->cu;$m->is_admin=false;$m->is_owner=false;$m->permissions='view_reports';$m->save();$service=new NativeCashFlowForecast();$before=$service->build(auth()->user(),$this->input());$owner=User::factory()->create(['account_id'=>$this->account->id]);$hidden=$this->invoice->replicate();$hidden->user_id=$owner->id;$hidden->assigned_user_id=null;$hidden->number='hidden-forecast';$hidden->saveQuietly();$other=$this->invoice->replicate();$other->company_id=Company::factory()->create(['account_id'=>$this->account->id])->id;$other->number='other-tenant';$other->saveQuietly();$after=$service->build(auth()->user(),$this->input());$this->assertSame($before['source_snapshot_sha256'],$after['source_snapshot_sha256']);$this->assertSame($before['scenarios'],$after['scenarios']);}
}
