<?php
namespace Tests\Integration;
use App\Models\{Invoice,User};
use App\Services\Receivables\CashFlowScenarioRuns;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\{Bus,DB,Mail};
use Symfony\Component\HttpKernel\Exception\HttpException;
use Tests\{MockAccountData,TestCase};
class CashFlowScenarioRunsTest extends TestCase {
    use MockAccountData,DatabaseTransactions;
    protected function setUp(): void {parent::setUp();Bus::fake()->except([\App\Jobs\Company\CreateCompanyTaskStatuses::class]);Mail::fake();$this->makeTestData();Bus::fake();config(['ninja.cash_flow_forecast_enabled'=>true,'ninja.db.multi_db_enabled'=>false]);request()->headers->set('X-API-TOKEN',$this->token);$s=$this->client->settings;$s->currency_id='1';$this->client->settings=$s;$this->client->saveQuietly();DB::table('invoices')->where('id',$this->invoice->id)->update(['status_id'=>Invoice::STATUS_SENT,'balance'=>'12.000000','due_date'=>'2026-10-03','is_deleted'=>false,'deleted_at'=>null]);}
    private function command(): array {$forecast=['start_date'=>'2026-10-02','end_date'=>'2026-10-04','scenarios'=>[['version'=>'base_v1','collection_basis_points'=>5000,'delay_days'=>0,'opening_minor_by_currency'=>['USD'=>'100'],'planned_outflows'=>[]]]];$hash=(new \App\Services\Receivables\NativeCashFlowForecast())->build(auth()->user(),$forecast)['source_snapshot_sha256'];return ['expected_source_snapshot_sha256'=>$hash,'operation_key'=>'forecast_record_operation_0001','expected_native_actor_id'=>$this->user->hashed_id,'forecast_input'=>['start_date'=>'2026-10-02','end_date'=>'2026-10-04','scenarios'=>[['version'=>'base_v1','collection_basis_points'=>5000,'delay_days'=>0,'opening_minor_by_currency'=>['USD'=>'100'],'planned_outflows'=>[]]]]];}
    private function locator(array $command): array {unset($command['forecast_input'],$command['expected_source_snapshot_sha256']);return $command;}
    private function financialRows(): array {$r=[];foreach(['invoices','payments','paymentables','clients','company_ledgers','activities','jobs']as$t)$r[$t]=DB::table($t)->orderBy('id')->get()->toJson();return $r;}
    private function denied(callable $action,int $status): void {try{$action();$this->fail('Denied native record operation succeeded');}catch(HttpException $e){$this->assertSame($status,$e->getStatusCode());}}
    public function testRecordAndAuthorisedExactReplayNeverChangeFinancialDomains(): void {$service=new CashFlowScenarioRuns();$c=$this->command();$before=$this->financialRows();$first=$service->save($this->user,$c);$this->assertSame('PLANNING_RECORD_ONLY',$first['write_authority']);$again=$service->save($this->user,$c);$this->assertTrue($again['replayed']);$this->assertSame($first['run_id'],$again['run_id']);$this->assertSame(1,DB::table('cash_flow_scenario_runs')->count());$this->assertSame($before,$this->financialRows());Bus::assertNothingDispatched();Mail::assertNothingSent();Mail::assertNothingQueued();}
    public function testScenarioSaveLocksCurrentInvoiceAndClientSources(): void {
        $command=$this->command();$connection=DB::connection();$connection->flushQueryLog();$connection->enableQueryLog();
        try{(new CashFlowScenarioRuns())->save($this->user,$command);}finally{$connection->disableQueryLog();}
        $queries=$connection->getQueryLog();
        $lockedInvoices=array_filter($queries,fn($query)=>str_contains(strtolower($query['query']),'invoices')&&str_contains(strtolower($query['query']),'for update'));
        $lockedClients=array_filter($queries,fn($query)=>str_contains(strtolower($query['query']),'clients')&&str_contains(strtolower($query['query']),'for update'));
        $this->assertNotEmpty($lockedInvoices,'Scenario persistence must hold native invoice rows until the immutable run commits.');
        $this->assertNotEmpty($lockedClients,'Scenario persistence must hold native client/currency scope until the immutable run commits.');
    }
    public function testReadIsImmutableHistoricalResultRatherThanRecalculation(): void {$service=new CashFlowScenarioRuns();$c=$this->command();$first=$service->save($this->user,$c);DB::table('invoices')->where('id',$this->invoice->id)->update(['balance'=>'10.000000']);$before=$this->financialRows();$r=$service->read($this->user,$this->locator($c));$this->assertTrue($r['read_only']);$this->assertSame('NONE',$r['write_authority']);$this->assertSame('RECORDED',$r['state']);$this->assertSame(json_encode($first),json_encode($r['receipt']));$this->assertSame($before,$this->financialRows());}
    public function testMissingRecordGrantsNoReplayOrWriteAuthority(): void {$service=new CashFlowScenarioRuns();$before=$this->financialRows();$r=$service->read($this->user,$this->locator($this->command()));$this->assertSame('NOT_FOUND',$r['state']);$this->assertNull($r['receipt']);$this->assertFalse($r['automatic_replay_allowed']);$this->assertSame(0,DB::table('cash_flow_scenario_runs')->count());$this->assertSame($before,$this->financialRows());}
    public function testChangedPayloadConflictsWithOriginalIdentity(): void {$service=new CashFlowScenarioRuns();$c=$this->command();$service->save($this->user,$c);$c['forecast_input']['scenarios'][0]['collection_basis_points']=10000;$this->denied(fn()=>$service->save($this->user,$c),409);$this->assertSame(1,DB::table('cash_flow_scenario_runs')->count());}
    public function testCurrentDatabaseRevocationAlsoDeniesRecordedReadAndReplay(): void {$service=new CashFlowScenarioRuns();$c=$this->command();$service->save($this->user,$c);DB::table('company_user')->where('company_id',$this->company->id)->where('user_id',$this->user->id)->update(['is_admin'=>false,'is_owner'=>false,'permissions'=>'']);$this->denied(fn()=>$service->read($this->user,$this->locator($c)),403);$this->denied(fn()=>$service->save($this->user,$c),403);}
    public function testHistoricalAmountsRemainProtectedByCurrentObjectAcl(): void {$service=new CashFlowScenarioRuns();$c=$this->command();$service->save($this->user,$c);DB::table('company_user')->where('company_id',$this->company->id)->where('user_id',$this->user->id)->update(['is_admin'=>false,'is_owner'=>false,'permissions'=>'view_reports']);$owner=User::factory()->create(['account_id'=>$this->account->id]);DB::table('invoices')->where('id',$this->invoice->id)->update(['user_id'=>$owner->id,'assigned_user_id'=>null]);$this->denied(fn()=>$service->read($this->user,$this->locator($c)),403);}
    public function testChangedCurrentSourceCannotBeSavedAsPreviouslyReviewedForecast(): void {$c=$this->command();DB::table('invoices')->where('id',$this->invoice->id)->update(['balance'=>'10.000000']);$this->denied(fn()=>(new CashFlowScenarioRuns())->save($this->user,$c),409);$this->assertSame(0,DB::table('cash_flow_scenario_runs')->count());}
    public function testNativeActorMismatchDeniesBeforeRecordCreation(): void {$c=$this->command();$c['expected_native_actor_id']='anotherActor';$this->denied(fn()=>(new CashFlowScenarioRuns())->save($this->user,$c),403);$this->assertSame(0,DB::table('cash_flow_scenario_runs')->count());}
    public function testApiReadRequiresOnlyOriginalLocatorAndCannotApplyMoney(): void {$h=['X-API-TOKEN'=>$this->token,'X-Requested-With'=>'XMLHttpRequest'];$c=$this->command();$before=$this->financialRows();$this->postJson('/api/v1/commands/cash_flow_scenario_run',$c,$h)->assertOk()->assertJsonPath('state','RECORDED');$this->postJson('/api/v1/reports/cash_flow_scenario_run',$this->locator($c),$h)->assertOk()->assertJsonPath('read_only',true)->assertJsonPath('write_authority','NONE');$this->assertSame($before,$this->financialRows());}
}
